apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-dep-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: nginx
    servicePort: 80
